"""initial bacchus schema

Revision ID: 2ec204764a6b
Revises: 
Create Date: 2026-09-28 12:01:13.254051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec204764a6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('distributor_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'code', name='uq_zone_state_code')
    )
    op.create_index(op.f('ix_zones_state_id'), 'zones', ['state_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_area_zone_code')
    )
    op.create_index(op.f('ix_areas_state_id'), 'areas', ['state_id'], unique=False)
    op.create_index(op.f('ix_areas_zone_id'), 'areas', ['zone_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('STOCK_REQUEST', 'PAYMENT', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_table('distributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('distributor_code', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_distributors_area_id'), 'distributors', ['area_id'], unique=False)
    op.create_index(op.f('ix_distributors_distributor_code'), 'distributors', ['distributor_code'], unique=True)
    op.create_index(op.f('ix_distributors_state_id'), 'distributors', ['state_id'], unique=False)
    op.create_index(op.f('ix_distributors_zone_id'), 'distributors', ['zone_id'], unique=False)
    op.create_table('salespersons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salesperson_code', sa.String(length=50), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_salespersons_area_id'), 'salespersons', ['area_id'], unique=False)
    op.create_index(op.f('ix_salespersons_distributor_id'), 'salespersons', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_salespersons_salesperson_code'), 'salespersons', ['salesperson_code'], unique=True)
    op.create_index(op.f('ix_salespersons_state_id'), 'salespersons', ['state_id'], unique=False)
    op.create_index(op.f('ix_salespersons_zone_id'), 'salespersons', ['zone_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_distributor_id'), 'inventory', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_salesperson_id'), 'inventory', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_inventory_variant_id'), 'inventory', ['variant_id'], unique=False)
    # Inventory has two ownership levels (distributor or salesperson)
    # and two product levels (base product or variant). PostgreSQL UNIQUE
    # indexes treat NULLs as distinct, so four partial indexes are required
    # to prevent duplicate inventory positions at both ownership levels.
    op.create_index(
        'uq_inventory_distributor_no_variant',
        'inventory',
        ['distributor_id', 'product_id'],
        unique=True,
        postgresql_where=sa.text(
            'salesperson_id IS NULL AND variant_id IS NULL'
        ),
    )
    op.create_index(
        'uq_inventory_distributor_variant',
        'inventory',
        ['distributor_id', 'product_id', 'variant_id'],
        unique=True,
        postgresql_where=sa.text(
            'salesperson_id IS NULL AND variant_id IS NOT NULL'
        ),
    )
    op.create_index(
        'uq_inventory_salesperson_no_variant',
        'inventory',
        ['distributor_id', 'salesperson_id', 'product_id'],
        unique=True,
        postgresql_where=sa.text(
            'salesperson_id IS NOT NULL AND variant_id IS NULL'
        ),
    )
    op.create_index(
        'uq_inventory_salesperson_variant',
        'inventory',
        ['distributor_id', 'salesperson_id', 'product_id', 'variant_id'],
        unique=True,
        postgresql_where=sa.text(
            'salesperson_id IS NOT NULL AND variant_id IS NOT NULL'
        ),
    )
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_code', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_area_id'), 'sellers', ['area_id'], unique=False)
    op.create_index(op.f('ix_sellers_distributor_id'), 'sellers', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_sellers_mobile'), 'sellers', ['mobile'], unique=False)
    op.create_index(op.f('ix_sellers_salesperson_id'), 'sellers', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_sellers_seller_code'), 'sellers', ['seller_code'], unique=True)
    op.create_index(op.f('ix_sellers_state_id'), 'sellers', ['state_id'], unique=False)
    op.create_index(op.f('ix_sellers_zone_id'), 'sellers', ['zone_id'], unique=False)
    op.create_table('stock_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='stockrequeststatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_requests_distributor_id'), 'stock_requests', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_stock_requests_request_code'), 'stock_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_stock_requests_salesperson_id'), 'stock_requests', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_stock_requests_status'), 'stock_requests', ['status'], unique=False)
    op.create_table('due_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('CREDIT_SALE', 'VERIFIED_PAYMENT', 'ADJUSTMENT', name='dueentrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_due_ledger_created_at'), 'due_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_due_ledger_distributor_id'), 'due_ledger', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_due_ledger_entry_type'), 'due_ledger', ['entry_type'], unique=False)
    op.create_index(op.f('ix_due_ledger_reference_id'), 'due_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_due_ledger_seller_id'), 'due_ledger', ['seller_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('movement_type', sa.Enum('OPENING', 'RECEIVED', 'ISSUED', 'SALE', 'RETURN', 'DAMAGE', 'ADJUSTMENT', name='inventorymovementtype'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_ledger_created_at'), 'inventory_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_inventory_id'), 'inventory_ledger', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_performed_by'), 'inventory_ledger', ['performed_by'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_product_id'), 'inventory_ledger', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_reference_id'), 'inventory_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_variant_id'), 'inventory_ledger', ['variant_id'], unique=False)
    op.create_table('payment_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_proof_code', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_id', sa.String(length=150), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='paymentproofstatus'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_distributor_id'), 'payment_proofs', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_payment_id'), 'payment_proofs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_payment_proof_code'), 'payment_proofs', ['payment_proof_code'], unique=True)
    op.create_index(op.f('ix_payment_proofs_salesperson_id'), 'payment_proofs', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_seller_id'), 'payment_proofs', ['seller_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_status'), 'payment_proofs', ['status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_number', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_distributor_id'), 'sales', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_number'), 'sales', ['sale_number'], unique=True)
    op.create_index(op.f('ix_sales_salesperson_id'), 'sales', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_sales_seller_id'), 'sales', ['seller_id'], unique=False)
    op.create_table('stock_request_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_request_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_request_id'], ['stock_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_request_items_product_id'), 'stock_request_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_request_items_stock_request_id'), 'stock_request_items', ['stock_request_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_stock_request_items_stock_request_id'), table_name='stock_request_items')
    op.drop_index(op.f('ix_stock_request_items_product_id'), table_name='stock_request_items')
    op.drop_table('stock_request_items')
    op.drop_index(op.f('ix_sales_seller_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_salesperson_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_distributor_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_payment_proofs_status'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_seller_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_salesperson_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_payment_proof_code'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_payment_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_distributor_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    op.drop_index(op.f('ix_inventory_ledger_variant_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_reference_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_product_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_performed_by'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_inventory_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_created_at'), table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_due_ledger_seller_id'), table_name='due_ledger')
    op.drop_index(op.f('ix_due_ledger_reference_id'), table_name='due_ledger')
    op.drop_index(op.f('ix_due_ledger_entry_type'), table_name='due_ledger')
    op.drop_index(op.f('ix_due_ledger_distributor_id'), table_name='due_ledger')
    op.drop_index(op.f('ix_due_ledger_created_at'), table_name='due_ledger')
    op.drop_table('due_ledger')
    op.drop_index(op.f('ix_stock_requests_status'), table_name='stock_requests')
    op.drop_index(op.f('ix_stock_requests_salesperson_id'), table_name='stock_requests')
    op.drop_index(op.f('ix_stock_requests_request_code'), table_name='stock_requests')
    op.drop_index(op.f('ix_stock_requests_distributor_id'), table_name='stock_requests')
    op.drop_table('stock_requests')
    op.drop_index(op.f('ix_sellers_zone_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_state_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_seller_code'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_salesperson_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_mobile'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_distributor_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_area_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(
        'uq_inventory_salesperson_variant',
        table_name='inventory',
        postgresql_where=sa.text(
            'salesperson_id IS NOT NULL AND variant_id IS NOT NULL'
        ),
    )
    op.drop_index(
        'uq_inventory_salesperson_no_variant',
        table_name='inventory',
        postgresql_where=sa.text(
            'salesperson_id IS NOT NULL AND variant_id IS NULL'
        ),
    )
    op.drop_index(
        'uq_inventory_distributor_variant',
        table_name='inventory',
        postgresql_where=sa.text(
            'salesperson_id IS NULL AND variant_id IS NOT NULL'
        ),
    )
    op.drop_index(
        'uq_inventory_distributor_no_variant',
        table_name='inventory',
        postgresql_where=sa.text(
            'salesperson_id IS NULL AND variant_id IS NULL'
        ),
    )
    op.drop_index(op.f('ix_inventory_variant_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_salesperson_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_distributor_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_salespersons_zone_id'), table_name='salespersons')
    op.drop_index(op.f('ix_salespersons_state_id'), table_name='salespersons')
    op.drop_index(op.f('ix_salespersons_salesperson_code'), table_name='salespersons')
    op.drop_index(op.f('ix_salespersons_distributor_id'), table_name='salespersons')
    op.drop_index(op.f('ix_salespersons_area_id'), table_name='salespersons')
    op.drop_table('salespersons')
    op.drop_index(op.f('ix_distributors_zone_id'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_state_id'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_distributor_code'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_area_id'), table_name='distributors')
    op.drop_table('distributors')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_areas_zone_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_state_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_zones_state_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('states')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('categories')

    # PostgreSQL enum types are schema-level objects and are not removed
    # automatically when their dependent tables are dropped.
    op.execute('DROP TYPE IF EXISTS inventorymovementtype')
    op.execute('DROP TYPE IF EXISTS dueentrytype')
    op.execute('DROP TYPE IF EXISTS paymentproofstatus')
    op.execute('DROP TYPE IF EXISTS stockrequeststatus')
    op.execute('DROP TYPE IF EXISTS notificationtype')

    # ### end Alembic commands ###
