"""add report submissions

Revision ID: fa41c0f89e71
Revises: 2ec204764a6b
Create Date: 2026-09-29 10:33:10.537535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa41c0f89e71'
down_revision: Union[str, Sequence[str], None] = '2ec204764a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_resource_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('report_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_code', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('reporting_from', sa.Date(), nullable=False),
    sa.Column('reporting_to', sa.Date(), nullable=False),
    sa.Column('report_file_url', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'DISTRIBUTOR_REVIEW', 'RETURNED', 'DISTRIBUTOR_SUBMITTED', 'ADMIN_REVIEW', 'APPROVED', 'REJECTED', name='reportsubmissionstatus'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('distributor_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('admin_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_reviewed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distributor_reviewed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_submissions_distributor_id'), 'report_submissions', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_report_submissions_report_code'), 'report_submissions', ['report_code'], unique=True)
    op.create_index(op.f('ix_report_submissions_report_type'), 'report_submissions', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_submissions_salesperson_id'), 'report_submissions', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_report_submissions_seller_id'), 'report_submissions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_report_submissions_status'), 'report_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_submissions_status'), table_name='report_submissions')
    op.drop_index(op.f('ix_report_submissions_seller_id'), table_name='report_submissions')
    op.drop_index(op.f('ix_report_submissions_salesperson_id'), table_name='report_submissions')
    op.drop_index(op.f('ix_report_submissions_report_type'), table_name='report_submissions')
    op.drop_index(op.f('ix_report_submissions_report_code'), table_name='report_submissions')
    op.drop_index(op.f('ix_report_submissions_distributor_id'), table_name='report_submissions')
    op.drop_table('report_submissions')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
